2019-08-29 13:36:22,492 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 13:36:32,143 ERROR: Exception on /edit_profile [POST] [in /Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/app/routes.py", line 93, in edit_profile
    db.session.commit()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/grantgeorge/w/flask-tutorials/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('grant', 'I am the great Jenkins that has ever lived', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-08-29 13:43:00,159 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 13:56:42,522 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 13:56:46,479 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 14:29:32,572 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 14:30:10,131 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
2019-08-29 14:35:20,152 INFO: Microblog startup [in /Users/grantgeorge/w/flask-tutorials/microblog/app/__init__.py:44]
